Repository TheoBerglin/TutorialGIT, pull requests merged in 2019-03, with the labels that each got.

#139 81 nodeattack
  graph/Graph.m
  graph/_tests/test_nodeattack.m
  graph/measures/_tests/get_test_struct.m
  graph/measures/nodal/_tests/test_zscore.m
  graph/measures/nodal/_tests/test_zscore_in.m
  graph/measures/nodal/_tests/test_zscore_out.m
Labels: Graph

#142 4 edgeattack
  graph/Graph.m
  graph/_tests/test_edgeattack.m
  graph/measures/_tests/get_test_struct.m
Labels: Graph

#140 131 averaging functions
  graph/Graph.m
  graph/measures/_tests/execute_graph_measure_test.m
  graph/measures/_tests/main_measure_test.m
  graph/measures/global/_tests/test_degree_average.m
  graph/measures/global/_tests/test_degree_in_average.m
  graph/measures/global/_tests/test_degree_out_average.m
  graph/measures/global/_tests/test_eccentricity_average.m
  graph/measures/global/_tests/test_eccentricity_in_average.m
  graph/measures/global/_tests/test_eccentricity_out_average.m
  graph/measures/global/_tests/test_strength_average.m
  graph/measures/global/_tests/test_strength_in_average.m
  graph/measures/global/_tests/test_strength_out_average.m
  graph/measures/global/clustering_average.m
  graph/measures/global/degree_average.m
  graph/measures/global/degree_in_average.m
  graph/measures/global/degree_out_average.m
  graph/measures/global/eccentricity_average.m
  graph/measures/global/eccentricity_in_average.m
  graph/measures/global/eccentricity_out_average.m
  graph/measures/global/global_efficiency_average.m
  graph/measures/global/global_efficiency_in_average.m
  graph/measures/global/global_efficiency_out_average.m
  graph/measures/global/local_efficiency_average.m
  graph/measures/global/strength_average.m
  graph/measures/global/strength_in_average.m
  graph/measures/global/strength_out_average.m
Labels: Graph, Measures, enhancement

#143 141 characteristics measures
  graph/measures/global/_tests/test_characteristic_pathlength.m
  graph/measures/global/_tests/test_characteristic_pathlength_in.m
  graph/measures/global/_tests/test_characteristic_pathlength_out.m
  graph/measures/global/_tests/test_characteristic_pathlength_wsg.m
  graph/measures/global/_tests/test_characteristic_pathlength_wsg_in.m
  graph/measures/global/_tests/test_characteristic_pathlength_wsg_out.m
  graph/measures/global/characteristic_pathlength.m
  graph/measures/global/characteristic_pathlength_in.m
  graph/measures/global/characteristic_pathlength_out.m
  graph/measures/global/characteristic_pathlength_wsg.m
  graph/measures/global/characteristic_pathlength_wsg_in.m
  graph/measures/global/characteristic_pathlength_wsg_out.m
Labels: Graph, Measures, enhancement

#144 130 remove average
  graph/Graph.m
Labels: Graph, Removal

#153 149 randomize folder structure
  graph/randomize/matrices/matrix_example.txt
  graph/randomize/randomize_analysis/remove_later.txt
  graph/randomize/randomize_functions/remove_later_2.txt
Labels: Extra

#156 155 clustering average bug
  graph/Graph.m
  graph/measures/global/_tests/test_clustering_global.m
  graph/measures/global/clustering_global.m
Labels: Measures, bug

#157 147 global measures
  graph/randomize/randomize_analysis/calculate_global_measures.m
  graph/randomize/randomize_analysis/remove_later.txt
Labels: enhancement

#158 150 kolmogorov smirnov
  graph/randomize/randomize_analysis/kolmogorov_smirnov.m
Labels: enhancement

#154 71 move current
  graph/randomize/randomize_functions/randomize_braph_BD.m
  graph/randomize/randomize_functions/randomize_braph_BU.m
  graph/randomize/randomize_functions/randomize_braph_WD.m
  graph/randomize/randomize_functions/randomize_braph_WU.m
Labels: Extra

#163 162 giovannis methods
  graph/randomize/randomize_functions/randm_giovanni_bd.m
  graph/randomize/randomize_functions/randm_giovanni_bu.m
  graph/randomize/randomize_functions/remove_later_2.txt
Labels: Extra

#161 148 test validity
  graph/randomize/randomize_analysis/calculate_global_measures.m
  graph/randomize/randomize_analysis/run_randomization.m
  graph/randomize/randomize_analysis/run_validation.m
  graph/randomize/randomize_analysis/test_randomization.m
Labels: Extra, enhancement

#166 61 participation
  graph/Graph.m
  graph/GraphBD.m
  graph/GraphBU.m
  graph/GraphWD.m
  graph/GraphWU.m
  graph/measures/nodal/_tests/test_participation.m
  graph/measures/nodal/_tests/test_participation_in.m
  graph/measures/nodal/_tests/test_participation_out.m
  graph/measures/nodal/participation.m
  graph/measures/nodal/participation_in.m
  graph/measures/nodal/participation_out.m
Labels: Measures, enhancement

#167 151 standard matrices
  graph/randomize/matrices/create_random_matrices.m
  graph/randomize/matrices/dens_0.050_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.050_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.100_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.100_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.150_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.150_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.200_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.200_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.250_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.250_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.300_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.300_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.350_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.350_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.400_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.400_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.450_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.450_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.500_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.500_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.550_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.600_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.600_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.650_nodes_100_bin_undir.txt
  graph/randomize/matrices/dens_0.700_nodes_100_bin_dir.txt
  graph/randomize/matrices/dens_0.700_nodes_100_bin_undir.txt
Labels: Extra

#169 105 zscore bug
  graph/Graph.m
  graph/measures/_tests/execute_graph_measure_test.m
  graph/measures/nodal/_tests/test_participation.m
  graph/measures/nodal/_tests/test_participation_in.m
  graph/measures/nodal/_tests/test_participation_out.m
  graph/measures/nodal/_tests/test_zscore.m
  graph/measures/nodal/_tests/test_zscore_in.m
  graph/measures/nodal/_tests/test_zscore_out.m
Labels: Measures, bug

#171 72 randomize analysis
  graph/randomize/randomize_analysis/data/speed/speed_null_model_und_sign_combo_gio.mat
  graph/randomize/randomize_analysis/test_randomization_speed.m
Labels: Extra

#174 173 test method
  graph/randomize/randomize_functions/randm_giovanni_bd_fix.m
  graph/randomize/randomize_functions/randm_giovanni_bd_no_fix.m
  graph/randomize/randomize_functions/randm_giovanni_bu_fix.m
  graph/randomize/randomize_functions/randm_giovanni_bu_no_fix.m
Labels: Extra

#179 175 distribute weights
  graph/randomize/randomize_functions/distribute_weights_directed.m
  graph/randomize/randomize_functions/distribute_weights_undirected.m
  graph/randomize/randomize_functions/randm_giovanni_bu.m
Labels: Rewrite, enhancement

#180 177 gio signed
  graph/randomize/randomize_functions/randm_giovanni_bd_fix.m
  graph/randomize/randomize_functions/randm_giovanni_bu_fix.m
Labels: enhancement

#184 183 plot script
  graph/randomize/randomize_analysis/plot_distributions.m
Labels: Extra

#181 176 randomize main
  graph/randomize/randomize_functions/randomize.m
Labels: enhancement

#186 Renamed, commented etc
  graph/randomize/randomize_functions/old_randomize_braph_BD.m
  graph/randomize/randomize_functions/old_randomize_braph_BU.m
  graph/randomize/randomize_functions/old_randomize_braph_WD.m
  graph/randomize/randomize_functions/old_randomize_braph_WU.m
  graph/randomize/randomize_functions/randm_giovanni_bd_fix.m
  graph/randomize/randomize_functions/randm_giovanni_bu_fix.m
  graph/randomize/randomize_functions/randomize_braph_BD.m
  graph/randomize/randomize_functions/randomize_braph_BU.m
Labels: Extra

#187 182 table presentation
  graph/randomize/randomize_analysis/table_presentation.m
Labels: Extra

#189 62 smallworldness
  graph/Graph.m
  graph/GraphBD.m
  graph/GraphBU.m
  graph/GraphWD.m
  graph/GraphWU.m
  graph/measures/global/smallworldness.m
  graph/measures/global/smallworldness_wsg.m
Labels: Graph, Measures, Rewrite

#190 188 randomize cleanup
  graph/Graph.m
  graph/GraphBD.m
  graph/GraphBU.m
  graph/GraphWD.m
  graph/GraphWU.m
  graph/randomize/randomize_functions/randomize.m
Labels: Graph, Rewrite
